# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' ADMM algorithm for estimating (normalized) graph Laplacian given v0 and theta0
#' 
#' @param `s` an estimated covariance matrix, such as the sample covariance matrix
#' @param `theta0` A given graph filter parameter
#' @param `v` A given degree vector
#' @param `rho` ADMM parameter 
#' @param `lambda` Tuning parameter
#' @param `model` A character specifying which type of Laplacian to use
#' @export
ADMM_L2 <- function(s, theta0, v, rho, lambda, model, Z_ini, W_ini, eps_thre, eps_abs, eps_rel, max_iter, verbose) {
    .Call('_SGM_ADMM_L2', PACKAGE = 'SGM', s, theta0, v, rho, lambda, model, Z_ini, W_ini, eps_thre, eps_abs, eps_rel, max_iter, verbose)
}

#' Added 10/09/2024
#' @export
ADMM_L2_Zero <- function(SS, theta0, v, rho, AA, model, Z_ini, W_ini, eps_thre, eps_abs, eps_rel, max_iter, verbose) {
    .Call('_SGM_ADMM_L2_Zero', PACKAGE = 'SGM', SS, theta0, v, rho, AA, model, Z_ini, W_ini, eps_thre, eps_abs, eps_rel, max_iter, verbose)
}

#' Added 10/9/2024
#' @export
ADMM_L2_seq <- function(S, theta0, v0, Rho, Lambda, model, ini, eps_thre, eps_abs, eps_rel, max_iter, verbose) {
    .Call('_SGM_ADMM_L2_seq', PACKAGE = 'SGM', S, theta0, v0, Rho, Lambda, model, ini, eps_thre, eps_abs, eps_rel, max_iter, verbose)
}

#' Added 10/9/2024
#' @export
ADMM_Lap <- function(SS, V0, rho, lambda, model, ZZ_ini, WW_ini, phi_ini, eps_thre, eps_abs, eps_rel, max_iter, Z_max_iter, Z_conv_abs, Z_conv_rel, verbose) {
    .Call('_SGM_ADMM_Lap', PACKAGE = 'SGM', SS, V0, rho, lambda, model, ZZ_ini, WW_ini, phi_ini, eps_thre, eps_abs, eps_rel, max_iter, Z_max_iter, Z_conv_abs, Z_conv_rel, verbose)
}

#' Added 10/09/2024
#' @export
ADMM_Lap_Zero <- function(SS, V0, rho, AA, model, ZZ_ini, WW_ini, phi_ini, eps_thre, eps_abs, eps_rel, max_iter, Z_max_iter, Z_conv_abs, Z_conv_rel, verbose) {
    .Call('_SGM_ADMM_Lap_Zero', PACKAGE = 'SGM', SS, V0, rho, AA, model, ZZ_ini, WW_ini, phi_ini, eps_thre, eps_abs, eps_rel, max_iter, Z_max_iter, Z_conv_abs, Z_conv_rel, verbose)
}

