# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ADMM_L2 <- function(s, theta0, v, rho, lambda, model, Z_ini, W_ini, eps_thre, eps_abs, eps_rel, max_iter, verbose) {
    .Call(`_SGM_ADMM_L2`, s, theta0, v, rho, lambda, model, Z_ini, W_ini, eps_thre, eps_abs, eps_rel, max_iter, verbose)
}

ADMM_L2_Zero <- function(SS, theta0, v, rho, AA, model, Z_ini, W_ini, eps_thre, eps_abs, eps_rel, max_iter, verbose) {
    .Call(`_SGM_ADMM_L2_Zero`, SS, theta0, v, rho, AA, model, Z_ini, W_ini, eps_thre, eps_abs, eps_rel, max_iter, verbose)
}

ADMM_L2_seq <- function(S, theta0, v0, Rho, Lambda, model, ini, eps_thre, eps_abs, eps_rel, max_iter, verbose) {
    .Call(`_SGM_ADMM_L2_seq`, S, theta0, v0, Rho, Lambda, model, ini, eps_thre, eps_abs, eps_rel, max_iter, verbose)
}

ADMM_Lap <- function(SS, V0, rho, lambda, model, ZZ_ini, WW_ini, phi_ini, eps_thre, eps_abs, eps_rel, max_iter, Z_max_iter, Z_conv_abs, Z_conv_rel, verbose) {
    .Call(`_SGM_ADMM_Lap`, SS, V0, rho, lambda, model, ZZ_ini, WW_ini, phi_ini, eps_thre, eps_abs, eps_rel, max_iter, Z_max_iter, Z_conv_abs, Z_conv_rel, verbose)
}

ADMM_Lap_Zero <- function(SS, V0, rho, AA, model, ZZ_ini, WW_ini, phi_ini, eps_thre, eps_abs, eps_rel, max_iter, Z_max_iter, Z_conv_abs, Z_conv_rel, verbose) {
    .Call(`_SGM_ADMM_Lap_Zero`, SS, V0, rho, AA, model, ZZ_ini, WW_ini, phi_ini, eps_thre, eps_abs, eps_rel, max_iter, Z_max_iter, Z_conv_abs, Z_conv_rel, verbose)
}

